### ISSUE TITLE
Visual Studio crash when opening .ammy files

### ISSUE THREAD

**Issue by WasserEsser** [AmmyUI/AmmyUI#106]
Opening .ammy pages can cause a crash of Visual Studio.

When the crash happens, you can see the opened .ammy file with the entire text being colored white.

I'm guessing that it has a similar cause of the issue you fixed in https://github.com/AmmyUI/AmmyUI/commit/66ce7dac9993c491dcb2271ed93bca49e3be62d1.

**Comment by WasserEsser** [comment]
I think I found out when exactly it happens.
When you open a .cs file and an .ammy file immediately after and Visual Studio is not quite done parsing the .cs file completely yet and displaying all the lines, colors etc, Visual Studio will crash.

**Comment by aalex675** [comment]
We have this problem constantly, here's a stack trace if it helps:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at Microsoft.VisualStudio.Text.SnapshotSpan.TranslateTo(Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.SpanTrackingMode)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1+<GetTagsForBuffer>d__39[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1+<InternalGetTags>d__40[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.CollapsiblesFromTags(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Text.Tagging.IMappingTagSpan`1<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>>)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.InternalGetAllRegions(Microsoft.VisualStudio.Text.NormalizedSnapshotSpanCollection, Boolean, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.GetAllRegions(Microsoft.VisualStudio.Text.SnapshotSpan, Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.Outlining.CachingRegionProvider.GetSortedExposedRegions(Microsoft.VisualStudio.Text.SnapshotSpan)
   at Microsoft.VisualStudio.Text.Editor.Implementation.Outlining.OutliningHeaders+<ProvideSortedValues>d__3.MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.Outlining.OutliningControls`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Update(Microsoft.VisualStudio.Text.SnapshotSpan, Microsoft.VisualStudio.Text.SnapshotSpan)
   at Microsoft.VisualStudio.Text.Editor.Implementation.Outlining.OutliningMarginControls`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Update()
   at Microsoft.VisualStudio.Text.Editor.Implementation.Outlining.CachedOutliningMarginControls`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Update()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
