### ISSUE TITLE
Cant use fields with type "Action" and suffix "Property"

### ISSUE THREAD

**Issue by jurij** [AmmyUI/AmmyUI#127]
See:
[WpfApp2.zip](https://github.com/AmmyUI/AmmyUI/files/2093049/WpfApp2.zip)

If there is a field somewhere in the whole codebase with type `Action` and is named `(.*)Property`, the Build fails. Is there a reason for that?

File App.xaml.cs:

```
public partial class App : Application
{
    private Action _testProperty;
}
```

Build Error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Ammy compilation error: Nemerle.Core.AssertionException: assertion failed in file Type\Member\Member.nitra, line 169: Property 'DotNet.Member.FieldSymbol.Type' is not set'
   at DotNet.Member.FieldSymbol.get_Type()
   at Ammy.Backend.XamlSymbolLoader.IsDependencyProperty(Field memberDecl, String dependencyPropertyTypeName)
   at Ammy.Backend.XamlSymbolLoader.LoadType(SupportsInheritanceTypeSymbol type, TypeSymbol objectType, DependentPropertyEvalContext context, PlatformTypeNames platformTypeNames)
   at Ammy.Backend.CSharpBackend._N_registerParsedTypes_13269(_N_closureOf_Load_13211 _N_Load_cp_13268, TableScope tableScope)
   at Ammy.Backend.CSharpBackend._N_registerParsedTypes_13269(_N_closureOf_Load_13211 _N_Load_cp_13268, TableScope tableScope)
   at Ammy.Backend.CSharpBackend.Load(ISourceCodeProject project, NamespaceSymbol globalNamespace, TypeSymbol objectType, PlatformTypeNames platformTypeNames, DependentPropertyEvalContext context)
   at Ammy.Language.Start.RefreshProject(CancellationToken _cancellationToken, ImmutableArray`1 files, Object data)
   at Ammy.Build.AmmyProject.RefreshProject(String outputPath, String rootNamespace, String assemblyName)
   at Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate, Boolean needXamlGeneration)	WpfApp2	C:\Users\jk.SESAM\source\repos\WpfApp2\WpfApp2\<Default>	1	
```

`Build succeeded` with:

```
public partial class App : Application
{
    //private Action _testProperty;
}
```

**Comment by juRiii** [comment]
We just renamed all fields. Works for now, thank you
