### ISSUE TITLE
Visual Studio 2019 - Extension installing failed.

### ISSUE THREAD

**Issue by MairwunNx** [AmmyUI/AmmyUI#141]
I liked what you did and I wanted to try it, but the installation failed in Visual Studio 2019 Professional, I hope you can fix it or make another installer for 2019 Studio. Thank.

###### Cutted stack-trace:

```
6/17/2019 3:35:41 PM - Searching for applicable products...
6/17/2019 3:35:41 PM - Found installed product - Global Location
6/17/2019 3:35:41 PM - Found installed product - Visual Studio Build Tools 2017
6/17/2019 3:35:41 PM - Found installed product - Visual Studio Professional 2019
6/17/2019 3:35:41 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by uargb** [comment]
+1. Pleasu, update support for new studio version

**Comment by sypack** [comment]
last update of the nuget package is 2018.... this seems dead.

**Comment by ionoy** [comment]
Hello guys,

Ammy is not actively maintained anymore. I can upgrade the extension if anyone still needs it. You should also be able to do that yourself pretty easily. Just install Nemerle and build Ammy.sln. You'll need to modify https://github.com/AmmyUI/AmmyUI/blob/master/src/IDE/Ammy.VisualStudio/source.extension.vsixmanifest for 2019 support.

**Comment by Odepax** [comment]
Aside from VS 2019 support, is it possible to use it with VS code?

**Comment by ionoy** [comment]
@Odepax No, it's not possible.

**Comment by WrongBit** [comment]
Dear Ionoy, please pay some attention to the project! It's so interesting, but sink in previous era of VS2017. Now already VS2022 is available, but no hope we can use Ammy there. :(
