### ISSUE TITLE
Visual Studio extension exception

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#38]
VS 2015 community has reported extension exception. Some info from ActivityLog.xml 
```
<entry>
    <record>596</record>
    <time>2017/01/30 10:10:33.223</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.   
    at Ammy.VisualStudio.Service.Intellisense.QuickInfoSource.GetSymbolLocation(DeclarationSymbol symbol)   
    at Ammy.VisualStudio.Service.Intellisense.QuickInfoSource.SymbolToHint(DeclarationSymbol symbol)   
    at Ammy.VisualStudio.Service.Intellisense.QuickInfoSource.SpanToSymbol(IList`1 quickInfoContent, NSpan span, IAst ast, Boolean&amp; foundSomething)   
    at Ammy.VisualStudio.Service.Intellisense.QuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 quickInfoContent, ITrackingSpan&amp; applicableToSpan)
    at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()
    at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
    at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)   
    at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()</description>
  </entry>
```

**Comment by ionoy** [comment]
Thanks! Investigating it now.

**Comment by ionoy** [comment]
Alright, it should be fixed in the upcoming version.
