### ISSUE TITLE
Nemerle.Core.AssertionException

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#80]
After adding Ammy 1.2.71 to another project in solution compilation no longer possible
```
Ammy compilation error: Nemerle.Core.AssertionException: assertion failed in file Type\Member\Member.nitra, line 168: Property 'DotNet.Member.FieldSymbol.Type' is not set'
   at DotNet.Member.FieldSymbol.get_Type()
   at Ammy.Backend.XamlSymbolLoader.IsDependencyProperty(Field memberDecl, String dependencyPropertyTypeName)
   at Ammy.Backend.XamlSymbolLoader.LoadType(SupportsInheritanceTypeSymbol type, TypeSymbol objectType, DependentPropertyEvalContext context, PlatformTypeNames platformTypeNames)
   at Ammy.Backend.CSharpBackend._N_registerParsedTypes_13382(_N_closureOf_Load_13324 _N_Load_cp_13381, TableScope tableScope)
   at Ammy.Backend.CSharpBackend._N_registerParsedTypes_13382(_N_closureOf_Load_13324 _N_Load_cp_13381, TableScope tableScope)
   at Ammy.Backend.CSharpBackend._N_registerParsedTypes_13382(_N_closureOf_Load_13324 _N_Load_cp_13381, TableScope tableScope)
   at Ammy.Backend.CSharpBackend.Load(ISourceCodeProject project, NamespaceSymbol globalNamespace, TypeSymbol objectType, PlatformTypeNames platformTypeNames, DependentPropertyEvalContext context)
   at Ammy.Language.Start.RefreshProject(CancellationToken _cancellationToken, ImmutableArray`1 files, Object data)
   at Ammy.Build.AmmyProject.RefreshProject(String outputPath, String rootNamespace, String assemblyName)
   at Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)	conexx.models3d	C:\programs\conexx\conexx.total\app\conexx.models3d\<Default>	1	
```

**Comment by ionoy** [comment]
Seems like Ammy C# parser can't resolve some type in your local project. Do you use C# 6/7 features?

**Comment by isukces** [comment]
Yes. I use C# 6/7 features. 
I spend some time and found that the exception throws because of dependency property that is under turned off compiler directive.
```
#if __DP__
public double Height
{
    get { return (double)GetValue(HeightProperty); }
    set { SetValue(HeightProperty, value);}
}
private static DependencyProperty HeightProperty = DependencyProperty.Register("Height", typeof(double), typeof(HProfileBase), new PropertyMetadata(GeometryChanged));
#endif
```
So class `HProfileBase` doesn't have neither `Height` nor `HeightProperty` member.

It would be helpful to catch this exception and provide error message containing file and property name that causes problem.

**Comment by ionoy** [comment]
Thanks for investigating. I will think about a solution for this.
