### ISSUE TITLE
ParseException on using Grid.Column on a Grid that is inside another Grid

### ISSUE THREAD

**Issue by theweavrs** [AmmyUI/AmmyUI#81]
Sorry if the title is a bit confusing but that pretty much sums it up. Now to the example:

```
Grid "ExampleGrid" {
#ThreeColumns("*", "2*", "Auto"),
Background: Black
Grid "ChildGrid" {
Grid.Column: "1" //exception here!!
}
//further code here
}
```
I am using this with AvaloniaUI but the syntax is the same for WPF so I don't think its Avalonia specific.

**Comment by ionoy** [comment]
Can you post a full example?

This doesn't fail for me on latest Ammy (1.2.71)

```
UserControl "WpfApp3.NewControl1" {
Grid "ExampleGrid" {
#ThreeColumns("*", "2*", "Auto"),
Background: Black
Grid "ChildGrid" {
Grid.Column: "1" //exception here!!
}
//further code here
}
}
```

**Comment by theweavrs** [comment]
Here you go:
```
Window "AvaloniaApplication1.MainWindow"
{
  Title: "Bread Player"
  Name: "MainWindow1"
  Grid 
  { 
	Grid "playbarGrid"	
	{
		VerticalAlignment: Bottom
		Height: "70"
		Background: Purple
		#FiveColumns("300", "Auto", "2*", "Auto", "Auto") 
		
       Grid "ChildGrid" {
                Grid.Column: 0, //exception here
                Background: Black
}
	StackPanel
		  {
		  Grid.Column: 0
			Orientation: "Horizontal"
			VerticalAlignment: "Stretch"
			StackPanel "tagsPanel"
			{
			  Orientation: "Vertical"
			  Margin: "20,0,0,0"
			  VerticalAlignment: "Center"
			  
			}
			
		  }	
		
  TextBlock {
  Grid.Column: 1
    Text: "00:00"
    HorizontalAlignment: "Left"
    VerticalAlignment: "Center"
    Foreground: "#FFE5E5E5"
    Margin: "0,0,0,0"
    FontSize: "12"
  }
  Slider "positionSlider" {
    HorizontalAlignment: "Stretch"
    VerticalAlignment: "Center"
    Maximum: "100"
    Value: "10"
    Grid.Column: "2"
    Margin: "10,0,10,0"
  }
  TextBlock {
    Grid.Column: "3"
    Text: "01:00"
    VerticalAlignment: "Center"
    HorizontalAlignment: "Right"
    Foreground: "#FFE5E5E5",
	Margin: "0,0,20,0"
    FontSize: "12"
  }


			StackPanel 
			{		
				HorizontalAlignment: Stretch  
				Name: "controlsPanel"
				Orientation: "Horizontal"
				Grid.Column: "4"				
			}
			
	
	} 
  }
}
```

Here's the exception:
```
ParseException: Cannot find a property named "Column" in the type Avalonia.Controls.Grid
```
And the second one:
```
LoadException: Error loading XAML: OmniXaml.ParseException: Cannot find a property named "Column" in the type Avalonia.Controls.Grid

   at Glass.Core.Guard.CheckForCondition[T,TException](T item, Predicate`1 p, Func`1 createException)

   at Glass.Core.Guard.ThrowIfNull[TException](Object item, Func`1 createException)

   at OmniXaml.Typing.Member.LookupType()

   at Avalonia.Markup.Xaml.Context.AvaloniaXamlType.LookupMember(String name)

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.ConvertAttributeToNode(XamlType containingType, AttributeAssignment rawAttributeAssignment)

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<>c__DisplayClass8_0.<CommonNodesOfElement>b__0(AttributeAssignment a)

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<CommonNodesOfElement>d__8.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseChildren>d__16.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseNestedElements>d__10.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseExpandedElement>d__9.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseChildren>d__16.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseNestedElements>d__10.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseExpandedElement>d__9.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseChildren>d__16.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseNestedElements>d__10.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseExpandedElement>d__9.MoveNext()

   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.SetNextInstruction()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseMembersOfObject>d__39.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseEmptyElement>d__26.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseCollectionInsideThisProperty>d__34.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseNestedProperties>d__31.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseCollectionInsideThisProperty>d__34.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()

   at OmniXaml.Parsers.Parser.InstructionParser.<Parse>d__23.MoveNext()

   at OmniXaml.MemberDependencyNodeSorter.<Sort>d__11.MoveNext()

   at OmniXaml.XmlParser.Parse(IEnumerable`1 xamlNodes)

   at OmniXaml.XmlParser.Parse(IXmlReader stream)

   at OmniXaml.XmlLoader.Load(Stream stream, IParser parser)

```

**Comment by ionoy** [comment]
This error is from Avalonia parser. Seems like resulting XAML was something like this:
```
<Grid Column="1">
...
</Grid>
```
when it should be

```
<Grid Grid.Column="1"
...
</Grid>
```

This meas that Column property was not correctly resolved as an attached property by Ammy backend. If I'm being honest, I haven't really tested it much with Avalonia, so these errors are expected. I will be able 
to look into it pretty soon, but if you want to help, I could provide guidance. Contact me on gitter if you are interested.

Thanks!

**Comment by theweavrs** [comment]
@ionoy yes you are right. Just went and saw the resulting XAML.

As for helping, I would like that very much. Currently, I am having network issues so cannot immediately come and chat but I will come as soon as they are resolved.

Thanks again.
