### ISSUE TITLE
combine not working

### ISSUE THREAD

**Issue by roy-t** [AmmyUI/AmmyUI#91]
I have the following .ammy file. As you can see creating Interaction Triggers is very repetitive.

```
using System.Windows.Interactivity;
UserControl "FooView" {

  Grid {
    Background: CornflowerBlue
      Interaction.Triggers: [
          System.Windows.Interactivity.EventTrigger {
            EventName: "PreviewMouseLeftButtonDown"
            InvokeCommandAction {
              Command: bind SelectCommand
            }
          }

          System.Windows.Interactivity.EventTrigger {
            EventName: "PreviewMouseRightButtonDown"
            InvokeCommandAction {
              Command: bind CreateCommand
            }
          }
      ]     
  }
}
```
So I came up with the following mixin

```
mixin BindEventToCommand (eventName = "", command = "") for Grid {
  combine System.Windows.Interactivity.Interaction.Triggers : [
    System.Windows.Interactivity.EventTrigger {
      EventName: $eventName
      System.Windows.Interactivity.InvokeCommandAction {
        Command: bind $command
      }
    }
  ]
}
```

This `mixin` works perfectly if I only use it once. But if I use it twice, like this I get a compilation error. 

```
using System.Windows.Interactivity;
using TexMorph.Viewer

UserControl "FooView" {  

  Grid {
    Background: CornflowerBlue
    #BindEventToCommand("PreviewMouseLeftButtonDown", "SelectCommand")
    #BindEventToCommand("PreviewMouseRightButtonDown", "CreateCommand")   
  }
}
```
The error:

```
Error		Ammy compilation error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ammy.Xaml.XamlValue.Build(XamlLocation start, Int32 indent)
   at Ammy.Xaml.XamlNode.Build(XamlLocation location, Int32 indent)
   at Ammy.Xaml.XamlNode.Build(XamlLocation location, Int32 indent)
   at Ammy.Xaml.XamlNode.Build(XamlLocation location, Int32 indent)
   at Ammy.Xaml.XamlElement.Build()
   at Ammy.Build.FileOutputWriter.GenerateTopNodes(XamlProjectMeta projectMeta)
   at Ammy.Build.FileOutputWriter.WriteFiles(Boolean generateMetaFile)
   at Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)	TexMorph	D:\Projects\C#\TexMorph\TexMorph\<Default>	1	
```
	
Did I use combine incorrectly here, or is this a bug in the combine keyword?

**Comment by ionoy** [comment]
This is definitely a bug. Ammy compiler shouldn't return any exceptions.

What you can do to remedy this situation at the moment is to define your mixin like this:

```
mixin BindEventToCommand (eventName = "", command = "") for Grid {
  combine System.Windows.Interactivity.Interaction.Triggers:
    System.Windows.Interactivity.EventTrigger {
      EventName: $eventName
      System.Windows.Interactivity.InvokeCommandAction {
        Command: bind $command
      }
    }
}
```

**Comment by roy-t** [comment]
Thanks for the work-around, works perfectly!

**Comment by ionoy** [comment]
This issue should be fixed now.

https://github.com/AmmyUI/AmmyUI/commit/6c78c55d2b6cbaadd73ba14a8e972788d825ff3b

I've uploaded a new version of Ammy to MyGet. Please check if it fixes you problem.

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> NuGet Package Manager -> Package Sources
Don't forget to click Update button there.

After that just switch Package Manager source to this new feed and `update-package Ammy.WPF`. You might need to restart Visual Studio since it uses assemblies from a package.

Thanks!
