### ISSUE TITLE
Creating custom bindable property makes ammy compile fail

### ISSUE THREAD

**Issue by vegardstn** [AmmyUI/AmmyUI#97]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Ammy compilation error: Nemerle.Core.AssertionException: assertion failed in file Type\Member\Member.nitra, line 168: Property 'DotNet.Member.FieldSymbol.Type' is not set'
   at DotNet.Member.FieldSymbol.get_Type()
   at Ammy.Backend.XamlSymbolLoader.IsDependencyProperty(Field memberDecl, String dependencyPropertyTypeName)
   at Ammy.Backend.XamlSymbolLoader.LoadType(SupportsInheritanceTypeSymbol type, TypeSymbol objectType, DependentPropertyEvalContext context, PlatformTypeNames platformTypeNames)
   at Ammy.Backend.CSharpBackend._N_registerParsedTypes_13381(_N_closureOf_Load_13323 _N_Load_cp_13380, TableScope tableScope)
   at Ammy.Backend.CSharpBackend._N_registerParsedTypes_13381(_N_closureOf_Load_13323 _N_Load_cp_13380, TableScope tableScope)
   at Ammy.Backend.CSharpBackend._N_registerParsedTypes_13381(_N_closureOf_Load_13323 _N_Load_cp_13380, TableScope tableScope)
   at Ammy.Backend.CSharpBackend.Load(ISourceCodeProject project, NamespaceSymbol globalNamespace, TypeSymbol objectType, PlatformTypeNames platformTypeNames, DependentPropertyEvalContext context)
   at Ammy.Language.Start.RefreshProject(CancellationToken _cancellationToken, ImmutableArray`1 files, Object data)
   at Ammy.Build.AmmyProject.RefreshProject(String outputPath, String rootNamespace, String assemblyName)
   at Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)
```

Currently I'm in need of a custom bindable property for an extension object to SKCanvasView (SkiaSharp), to add some color for an eventhandler inside a DataTemplate for cells in a grid, but the build fails with the above error.

This is the code that makes it fail:
```
public class DataGridSKCanvasView : SKCanvasView
{
        private Color _circleColor;
        public Color CircleColor { get => _circleColor; set { _circleColor = value; OnPropertyChanged(); } }

        public static readonly BindableProperty CircleColorProperty = BindableProperty.Create(
                nameof(CircleColor),
                typeof(Color),
                typeof(DataGridSKCanvasView)
                Color.Transparent));

        public DataGridSKCanvasView() : base() { }
}
```

**Comment by ionoy** [comment]
Hello @vegardstn,
Seems like it's a problem with C# 7 feature "get => ...;" It will be fixed in upcoming weeks, at the moment only C# 6 features work. Please, try replacing your getter declaration with older syntax and see if it works.

Thank!

**Comment by vegardstn** [comment]
The issue is still present, same error, after changing the get accessor to C# 6 style
